version: "3.9"
services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:latest
    networks:
      - app-net
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  app-net:
    name: external-network
    external: true
