version: "3.9"
services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:latest
    networks:
      - app-net
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend
    networks:
      - app-net
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./frontend
    networks:
      - app-net
    ports:
      - '80:80'
    depends_on:
      - backend

networks:
  app-net:
    name: external-network
    external: true
